# Base file, do not modifiy.
# Make changes in docker-compose.override.yml instead.
# See https://docs.docker.com/compose/extends/#example-use-case
version: '3'
services:
  lisk:
    image: lisk/core:${ENV_LISK_VERSION}
    volumes:
      - lisk-logs:/home/lisk/lisk/logs/
    ports:
      - ${ENV_LISK_HTTP_PORT}:${ENV_LISK_HTTP_PORT}
      - ${ENV_LISK_WS_PORT}:${ENV_LISK_WS_PORT}
    networks:
      - lisk
    depends_on:
      - db
    restart: on-failure
    entrypoint:
      [
        '/home/lisk/wait-for-it.sh',
        'db:5432',
        '--',
        'node',
        '/home/lisk/lisk/dist/index.js',
      ]
    command: ['-n', '${ENV_LISK_NETWORK}']
    environment:
      - LISK_DB_HOST=db
      - LISK_DB_USER=${ENV_LISK_DB_USER}
      - LISK_DB_PASSWORD=${ENV_LISK_DB_PASSWORD}
      - LISK_DB_NAME=${ENV_LISK_DB_DATABASE}
      - LISK_FILE_LOG_LEVEL=none
      - LISK_CONSOLE_LOG_LEVEL=info
      - LISK_CACHE_ENABLED=false

  db:
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - lisk
    restart: on-failure
    environment:
      - POSTGRES_DB=${ENV_LISK_DB_DATABASE}
      - POSTGRES_PASSWORD=${ENV_LISK_DB_PASSWORD}
      - POSTGRES_USER=${ENV_LISK_DB_USER}

networks:
  lisk:

volumes:
  db-data:
  lisk-logs:
