dist: 'trusty'
language: node_js
node_js:
  - '6.9.4'
cache:
  yarn: true
  directories:
    - test/lisk-js
services:
  - postgresql
addons:
  postgresql: '9.6'
install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn unzip
  - yarn
before_script:
  - createdb lisk_test
  - psql -d lisk_test -c "alter user "$USER" with password 'password';"
  - wget https://downloads.lisk.io/lisk-node/lisk-node-Linux-x86_64.tar.gz
  - tar -zxvf lisk-node-Linux-x86_64.tar.gz
  - cd test/lisk-js/; yarn; cd ../..
  - cp test/config.json test/genesisBlock.json .
  - node app.js --coverage=true &> .app.log &
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=7s05KDqmPWkwZ6nzU5WtznKkt5FKDE3kv
env:
  global:
    - HOST=http://0.0.0.0:4000
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST=test/api/peer.transactions.stress.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.transactions.votes.js TEST_TYPE='FUNC'
    - TEST=test/api/delegates.js TEST_TYPE='FUNC'
    - TEST=test/api/accounts.js TEST_TYPE='FUNC'
    - TEST=test/api/blocks.js TEST_TYPE='FUNC'
    - TEST=test/api/dapps.js TEST_TYPE='FUNC'
    - TEST=test/api/loader.js TEST_TYPE='FUNC'
    - TEST=test/api/multisignatures.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.dapp.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.blocks.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.signatures.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.transactions.collision.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.transactions.delegates.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.transactions.main.js TEST_TYPE='FUNC'
    - TEST=test/api/peer.transactions.signatures.js TEST_TYPE='FUNC'
    - TEST=test/api/peers.js TEST_TYPE='FUNC'
    - TEST=test/api/signatures.js TEST_TYPE='FUNC'
    - TEST=test/api/transactions.js TEST_TYPE='FUNC'

    - TEST=test/unit/helpers TEST_TYPE='UNIT'
    - TEST=test/unit/logic TEST_TYPE='UNIT'
    - TEST=test/unit/modules TEST_TYPE='UNIT'
script: 'npm run travis'
after_success:
    - bash .travis/after-success.sh $TRAVIS_BUILD_NUMBER ${TRAVIS_JOB_NUMBER#*.} $TEST_TYPE $TRAVIS_BUILD_DIR $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST_BRANCH;
after_failure:
  - bash .travis/report-failure.sh $TRAVIS_BUILD_NUMBER
  - cat .app.log

