# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _cors: 
      name: swagger_cors
      origin: '*'

    _compression: 
      name: swagger_compression
      level: 9      

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: lisk_params_validator

    # For more detail options https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0
    _swagger_params_parser:
      name: swagger_params_parser
      jsonOptions: {}
      urlencodedOptions:
        extended: false
      multerOptions:
        inMemory: true
      textOptions:
        type: "*/*"

    _json_error_handler:
      name: json_error_handler
      handle500Errors: false

    # For more details https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.10
    _swagger_security:
      name: swagger_security
      securityHandlersModule: helpers/swagger_security_handlers

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: _json_error_handler
      - _cors
      - _compression
      - _swagger_params_parser
      - _swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

