####################################################################################
# Copyright Â© 2020 Lisk Foundation
#
# See the LICENSE file at the top-level directory of this distribution
# for licensing information.
#
# Unless otherwise agreed in a custom licensing agreement with the Lisk Foundation,
# no part of this software, including this file, may be copied, modified,
# propagated, or distributed except according to the terms contained in the
# LICENSE file.
#
# Removal or modification of this copyright notice is prohibited.
####################################################################################
swagger: '2.0'

info:
  title: Lisk Forger API documentation
  description: |
    # Welcome!

    ## Access restrictions
    The API endpoints are by default restricted to a whitelist of IPs that can be found under `plugins.forger.whiteList` in the config.
    If it is required for your API to be accessible by the public, this can be achieved by changing `plugins.forger.whiteList` to `[]`.
    This will allow anyone to make requests to your application.

    ## Requests
    Chained filter parameters are logically connected with `AND`.
    `HTTP` is the supported URL schema by default.

    ## Responses
    The general response format is JSON (`application/json`).
    The responses for each API request have a common basic structure as shown below:
    ```javascript
    {
        "data": {}, //Contains the requested data.
        "meta": {}, //Contains additional metadata, e.g. the values of `limit` and `offset`.
    }
    ```
    ## List of endpoints
    All possible Forger API endpoints are listed below.
    Click on an endpoint to show the descriptions, details and examples.
  version: '1.0.32'
  contact:
    email: admin@lisk.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

# All paths relative to specified basePath
basePath: /api

# Tags for organizing operations
tags:
  - name: Forgers
    description: Forgers related API endpoints.

schemes:
  - http

paths:
  /voters:
    get:
      tags:
        - Forgers
      summary: Requests voters information for each delegate corresponding to local node
      description: |
        Requests voters information for each delegate corresponding to local node
      produces:
        - application/json
      responses:
        200:
          description: A list of delegates with voters
          schema:
            $ref: '#/definitions/VotersResponse'
        400:
          description: Malformed query or parameters.
          schema:
            $ref: '#/definitions/ErrorResponse'
        429:
          description: Too many requests, exceeded rate limit.
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/ErrorResponse'

  /forging:
    patch:
      tags:
        - Node
      summary: Toggles the forging status of a delegate.
      description: |
        Upon passing the correct password and address, forging will be enabled or disabled for the delegate of this particular node.
        The password can be generated locally by encrypting your passphrase, either by using Lisk Commander or with Lisk Elements.
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: data
          description: Password for decrypting passphrase of delegate with corresponding delegate address.
          required: true
          schema:
            type: object
            required:
              - password
              - address
              - forging
            properties:
              forging:
                type: boolean
                example: true
                description: Forging status of the delegate.
              password:
                type: string
                example: 'happy tree friends elephant tree'
                minLength: 5
                description: Password for decrypting passphrase of delegate.
              address:
                type: string
                example: 'CQP0xctZmnkorvJ+KU6YKT0eOIg='
                format: base64
                description: Address of the delegate.
      responses:
        200:
          description: Delegate forging toggled on or off.
          schema:
            $ref: '#/definitions/ForgingStatusResponse'
        400:
          description: Malformed query or parameters.
          schema:
            $ref: '#/definitions/ErrorResponse'
        429:
          description: Too many requests, exceeded rate limit.
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/ErrorResponse'

parameters:
  limit:
    in: query
    name: limit
    description: Limit applied to results.
    type: integer
    format: int32
    minimum: 1
    default: 10
  offset:
    name: offset
    in: query
    description: Offset value for results.
    type: integer
    format: int32
    minimum: 0
    default: 0

definitions:
  ErrorResponse:
    type: object
    required:
      - errors
    properties:
      errors:
        type: array
        items:
          type: object
          properties:
            message:
              description: Error message containing details of the error.
              example: Reason of the error
              type: string
              minLength: 1

  VotersResponse:
    type: object
    required:
      - data
    properties:
      data:
        description: List of forgers with voters.
        type: array
        items:
          $ref: '#/definitions/ForgerWithVoters'
      meta:
        $ref: '#/definitions/Meta'

  ForgingStatusResponse:
    type: object
    required:
      - data
      - meta
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ForgingStatus'
      meta:
        type: object
        properties:
          count:
            description: Number of records returned in response.
            type: integer
            minimum: 0

  ForgingStatus:
    type: object
    required:
      - forging
      - address
      - receivedFees
      - receivedRewards
      - producedBlocks
      - missedBlocks
    properties:
      forging:
        type: boolean
        example: true
        description: True if the delegate enabled forging.
      address:
        type: string
        example: 'CQP0xctZmnkorvJ+KU6YKT0eOIg='
        format: base64
        description: Address of the delegate.
      receivedFees:
        type: string
        example: '33333232323'
        description: Total fees received by a delagate.
      receivedRewards:
        type: string
        example: '33333232323'
        description: Total rewards received by a delagate.
      producedBlocks:
        type: integer
        example: '23'
        description: Total blocks produced by a delagate.
      missedBlocks:
        type: integer
        example: '2'
        description: Total blocks missed by a delagate.

  ForgingInfoResponse:
    type: object
    required:
      - data
    properties:
      data:
        description: List of forging delegates.
        type: array
        items:
          $ref: '#/definitions/ForgingInfo'
      meta:
        type: object

  Meta:
    type: object
    required:
      - limit
      - offset
    properties:
      limit:
        description: Limit applied to results.
        type: integer
        minimum: 1
        default: 10
      offset:
        description: Offset value for results.
        type: integer
        format: int32
        minimum: 0
        default: 0

  ForgerWithVoters:
    allOf:
      - $ref: '#/definitions/ForgerBasicInfo'
      - properties:
          voters:
            type: array
            items:
              type: object
              required:
                - address
                - voters
              properties:
                address:
                  type: string
                  example: nQFJsJYtRL/Aip9k1a/Otigdf7U=
                  description: |
                    The binary address in base64 format as defined in LIP-0018.
                amount:
                  type: string
                  example: 56072
                  description: Votes from that account

  ForgerBasicInfo:
    type: object
    required:
      - address
      - username
      - totalVotesReceived
    properties:
      address:
        type: string
        example: nQFJsJYtRL/Aip9k1a/Otigdf7U=
        description: |
          The binary address in base64 format as defined in LIP-0018.
      totalVotesReceived:
        type: string
        example: 1081560729258
        description: |
          The total votes received by the delegate.
          Represents the total amount of token that the delegates voters voted this delegate.
      username:
        type: string
        example: genesis_01
        description: |
          The delegates username.
          A delegate chooses the username by registering a delegate on the network.
          It is unique and cannot be changed later.

  Forger:
    allOf:
      - $ref: '#/definitions/ForgerBasicInfo'
      - required:
          - nextForgingTime
        properties:
          nextForgingTime:
            type: number
            example: 4368793
            description: |
              Returns the unix timestamp in second in which the forger will be able to forge the next block.
              Each slot has a time span of 10 seconds.
      nextForgingTime:
        type: number
        example: 4368793
        description: |
          Returns the unix timestamp in second in which the forger will be able to forge the next block.
          Each slot has a time span of 10 seconds.

  ForgingInfo:
    type: object
    required:
      - address
      - username
      - totalReceivedFees
      - totalReceivedRewards
      - totalProducedBlocks
      - totalVotesReceived
      - consecutiveMissedBlocks
    properties:
      address:
        type: string
        example: nQFJsJYtRL/Aip9k1a/Otigdf7U=
        description: |
          The binary address in base64 format as defined in LIP-0018.
      username:
        type: string
        example: genesis_01
        description: |
          The delegates username.
          A delegate chooses the username by registering a delegate on the network.
          It is unique and cannot be changed later.
      totalReceivedFees:
        type: string
        example: 1081560729258
        description: |
          The total fees received by the delegate.
          Represents the total amount of token that the delegates received for processing the transaction.
      totalReceivedRewards:
        type: string
        example: 1081560729258
        description: |
          The total rewards received by the delegate.
          Represents the total amount of token that the delegates received for processing the block.
      totalProducedBlocks:
        type: string
        example: 100
        description: |
          The total blocks generated by the delegate.
      totalVotesReceived:
        type: string
        example: 10
        description: |
          The total votes received by the delegate.
          Represents the total amount of token that the delegates voters voted this delegate.
      consecutiveMissedBlocks:
        type: string
        example: 10
        description: |
          Number of consecutive blocks missed by the delegate, used to determine if the delegate has to be banned.
